name: Relyance SCI Scan

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  execute-relyance-sci:
    name: Relyance SCI Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
